# Generated by Django 5.1.2 on 2024-10-27 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailydress', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stylecloth',
            name='cloth',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cloth', to='dailydress.cloth'),
        ),
        migrations.AlterField(
            model_name='stylecloth',
            name='style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='style_cloth', to='dailydress.style'),
        ),
    ]
